### ISSUE TITLE
Overlays z-index is not high enough for embedding in popups

### ISSUE THREAD

**Issue by AbelVM** [mapillary/mapillary-js#244] opened 2017-05-24 12:54 UTC
Looks like overlays'
```CSS
z-index: 10;
```
is not enough when embedding the viewer

**mapillary-js version**: latest

### Steps to Reproduce Behavior

 1. Embed the viewer within a Leaflet popup
 2. Open it

### Expected Behavior
The overlays are there

### Actual Behavior
No visible overlays (navigation, attribution, PoV, etc.)

### Workaround:
Just force the Z-index to any value above 99

```CSS
.domRenderer > div {
    z-index: 100 !important; 
}
```

**Comment by oscarlorentzon** [comment] 2017-05-24 13:19
@AbelVM Can you provide a minimal code example reproducing the problem?

**Comment by AbelVM** [comment] 2017-05-24 13:35
Wilco

**Comment by AbelVM** [comment] 2017-05-24 14:01
Done

http://bl.ocks.org/AbelVM/df695d58bbb28105f369ae866d780c5b

**Comment by oscarlorentzon** [comment] 2017-05-24 15:33
Thanks.

For some reason Leaflet sets the z-index of all canvas and svg elements inside the `.leaflet-map-pane` div.

https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L97-L98

This destroys the internal structure of the MJS element tree because we render on a canvas (plus create some svgs).

If you add a class to the MJS viewer div like this

`visor.classList.add('av-pano-viewer');`

and add the following CSS

```
.av-pano-viewer canvas,
.av-pano-viewer svg {
    z-index: initial;
}
```

you will override the Leaflet CSS that is causing the problem and it should work.

**Comment by AbelVM** [comment] 2017-05-24 15:44
:+1:

**Comment by oscarlorentzon** [comment] 2017-06-29 14:31
Closing this since the problem was caused by an external library with no change required in MapillaryJS.

**Closed by oscarlorentzon** 2017-06-29 14:31 UTC
