### ISSUE TITLE
CORS Block after loading multiple image ids in viewer (Application request limit reached)

### ISSUE THREAD

**Issue by MarvinDrude** [mapillary/mapillary-js#456] opened 2021-07-01 19:41 UTC
### Basic information

**MapillaryJS version**: `4.0.0`
**System/Browser**: `Windows/Chrome`

Hello guys,

at the moment I am making a geo guesser game that loads image ids one after another in like intervals of 30 seconds with the access token given in the developer menu of the mapillary site.

When I test playing for a while, I am not able to load any more image ids because I get a CORS error for 'localhost'.
Fun Fact: Trying to login into mapillary directly after that results into "Unable to perform operation, please try again later" and the console tells me that the request limit was reached. (Picture below)

![image](https://user-images.githubusercontent.com/24737821/124180746-f12a9400-dab4-11eb-9071-1249b2854de5.png)

Now is there any way to stop this limitation from happening?
I mean I don't spam requests. It is just normal use of the viewer api.

Thank you in advance.

**Comment by myarx** [comment] 2021-07-13 20:21
Hi, we're experiencing the same issue :(
Are there any additional information about the limitations? If they already strike in on normal usage during development, hard to imagine a productive application not suffering from it.
Marvin, were you able to figure out anything regarding this issue?
Thanks and kind regards

**Comment by MarvinDrude** [comment] 2021-07-13 20:26
I have an ongoing support ticket with email. Currently waiting for the second reply after the initial one. I keep it updated here if I have any news. They asked me how much Images I load in which time until I get blocked.

I calculated in 2:30 Minutes I had 14 seperate image loads by code and then navigated 5 times on average meaning 14 * 5 = 70 images loaded on total.

**Comment by MarvinDrude** [comment] 2021-07-15 07:08
Just got a update that they work on a fix. And that I get news in the future.

**Comment by oscarlorentzon** [comment] 2021-08-02 08:37
Closing because the root cause of this is related to the Mapillary API (not MapillaryJS) and is handled in the email support ticket.

**Closed by oscarlorentzon** 2021-08-02 08:37 UTC
