### ISSUE TITLE
Limited behavior when drawing detection box

### ISSUE THREAD

**Issue by todrobbins** [mapillary/mapillary-js#185] opened 2016-08-25 14:52 UTC
**[mapillary-js 1.6.0](https://github.com/mapillary/mapillary-js/releases/tag/v1.6.0)**:

When drawing a new detection, you can only expand the box to the right and down with your cursor. Is that an intentional design decision? It makes drawing boxes on the edges of images fairly difficult.

### Steps to Reproduce Behavior

 1. Enter edit mode for any image
 2. Click and trying dragging up and to the left

### Expected Behavior

Multi-directional expansion of detection boxes

### Actual Behavior

Can only draw to the right and down when creating a new detection box

**Comment by oscarlorentzon** [comment] 2016-08-26 13:26
Agree that it would be better to be able to create rectangles in any direction.

If you want to create rectangles in the corners other than the bottom right one, as of now the simplest way to do it is to create the rectangle and move or resize it afterwords. There are more mouse movement and clicks involved when doing it that way so not optimal of course.

Closing this issue as it is a duplicate of #163.

**Closed by oscarlorentzon** 2016-08-26 13:26 UTC
Labels: info-duplicate
