### ISSUE TITLE
Fill mode from init

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#115] opened 2016-05-02 21:38 UTC
Im trying to set fill mode directly after init, but it seems that there is some kind of race. It falls back to letterbox.

**Comment by oscarlorentzon** [comment] 2016-05-03 07:49
The recommended way to set the render mode initially is through the viewer options:

```
var viewer = new Mapillary.Viewer(
    "elementId",
    "clientId",
    "key",
    { renderMode: Mapillary.RenderMode.Fill }
);
```

The fact that it is not possible to generate the documentation at this moment (see #114) is the reason for this property not being documented.

This does not change the fact that it should work to set it at any time after the viewer has been created though.

**Comment by oscarlorentzon** [comment] 2016-06-28 11:45
This issue also affects calls to resize. If the component controller has not been initialized the resize calls will have no effect.

**Comment by tomwayson** [comment] 2016-06-28 23:56
I can confirm that this is causing (what appear to be) completely black images in our application, which doesn't use keys at all, and instead relies entirely on `moveTo()` for navication. I initialize the viewer in a hidden panel w/o any key, and later (after a user has clicked on a map location) show the hidden panel, call `resize()`, and then call `moveTo`, but as you mention above, the resize does not appear to work and the viewer is just showing the image in a 0 x 0 container.

**Comment by oscarlorentzon** [comment] 2016-06-29 11:51
@tomwayson Thanks for the input.

The issue is not related to what method is used for navigating the viewer. It works in the same way for `moveToKey`, `moveDir` and `moveCloseTo`. The problem is that calling `resize`, or `setRenderMode`, before the first node is set (i.e. the component controller and the viewer have been initialized and the first node loaded) does not have any effect. After the first node is set it works calling those methods. When you initialize the viewer with a key it will fetch that node in the background and will be initialized by the time you show the viewer and call `resize`. When not supplying a key to the viewer constructor it will only start initializing after you set the first node. Because you call resize before the node is set it does not have any effect right now.

**Comment by oscarlorentzon** [comment] 2016-06-29 11:52
Relies on fixing #116. When implementing a solution for this issue other unrelated RxJS unit tests starts to fail randomly.

**Closed** 2016-07-05 20:51 UTC
Labels: bug

**Comment by tomwayson** [comment] 2016-08-02 23:53
I can confirm that updating to 1.4.2 fixed the problem we were having.
