### ISSUE TITLE
Put a sequence slider in to complement the sequence stepper

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary-js#190] opened 2016-09-09 08:08 UTC
In order to fast-slide along a sequence and find relevant stops, under the sequence stepper there could be a slider through the sequence with little thumbs popping up as you slide it.

It would be great for blurring, scanning and selecting faster without needing to step.

**Comment by peterneubauer** [comment] 2016-09-09 08:09
related to https://github.com/mapillary/mapillary_elva/issues/658

**Comment by oscarlorentzon** [comment] 2016-09-12 20:06
Duplicate of #171 with some additional details. Closing this one.

**Closed by oscarlorentzon** 2016-09-12 20:06 UTC
Labels: affects-component, affects-design, feature
